/**
 * dsh 运行体的「隐藏子进程控制台窗口」预载 hook（纯字符串常量，不含运行时依赖）。
 *
 * 背景：dsh 的子进程服务（`@deepseek-ai/dsh-subprocess-local`）在 Windows 上 spawn
 * 子进程时只传 cwd / env / stdio / detached，没有 windowsHide；而本应用是 GUI 进程
 * （没有控制台窗口），于是 agent 每执行一条命令（bash -c、git、node 等）Windows 都会
 * 新建一个可见的控制台窗口——用户看到的就是「AI 对话过程中频繁弹出命令行窗口」。
 *
 * 修法：dsh 启动时用 `--require` 预载本 hook（文件写在 dsh home 下，见 harness 服务），
 * 把 child_process 各启动 API 的 windowsHide 默认置为 true。只改这一个默认值：
 * 参数形态、返回值、事件语义全部不变；hook 一切失败都静默忽略，不影响对话。
 *
 * 源码用 IIFE + 全局哨兵写成「可重复执行」：进程里被 `--require` 与 NODE_OPTIONS
 * 各预载一次（或路径大小写不同导致模块缓存未命中）也只生效一次，不会报重复声明。
 *
 * 独立成模块（不 import electron）是为了可被单测直接加载验证。
 * 注意：源码字符串内是「注入产物的文案」，注释一律用英文（硬编码中文检查会拦）。
 */

/** hook 文件名（写在 dsh home 下；dsh 每次启动重写内容） */
export const HIDE_CHILD_WINDOWS_HOOK_FILENAME = 'aiart-hide-child-windows.cjs'

/**
 * 把 `--require "<hook>"` 追加到既有 NODE_OPTIONS 后面。
 *
 * node 直启 dsh 时命令行 flag 已足够，这份 env 是为了覆盖两条 CLI 摸不到的路径：
 * npx 现场拉包（无 dsh 入口，只能靠环境变量）与 dsh 内部再拉起的 Node 子进程。
 *
 * 写进 NODE_OPTIONS 的路径有两条实测出来的规矩（都不是 Windows 的规矩，是 Node
 * 解析这个环境变量时的规矩）：
 * - 反斜杠必须换成正斜杠。Node 分词 NODE_OPTIONS 时把 `\` 当转义符直接吃掉，
 *   Windows 原生路径 `C:\Users\PS\...` 会变成 `C:UsersPS...`，预载失败并抛
 *   MODULE_NOT_FOUND（requireStack: internal/preload）。正斜杠路径在 Windows 上
 *   一样是绝对路径，Node 与 require 都能正常解析。
 * - 路径含空格（用户名带空格时 dsh home 必然含空格）必须双引号包裹。
 *
 * 命令行 `--require` 参数没有这层解析，所以仍用系统原生路径（见 harness 服务）。
 */
export function appendNodeRequireOption(current: string | undefined, hookPath: string): string {
  const entry = `--require "${toNodeOptionsPath(hookPath)}"`
  const trimmed = current?.trim()
  return trimmed ? `${trimmed} ${entry}` : entry
}

/** NODE_OPTIONS 里的路径一律用正斜杠（反斜杠会被 Node 当转义符吃掉） */
export function toNodeOptionsPath(path: string): string {
  return path.replace(/\\/g, '/')
}

/** hook 源码：自包含 CJS，幂等（重复执行只装一次） */
export const HIDE_CHILD_WINDOWS_HOOK_SOURCE = `'use strict';
// Generated by AIArtEngine (rewritten on every launch; do not edit by hand).
// dsh spawns subprocesses without windowsHide while the host is a GUI process with no
// console attached, so every agent command used to flash a console window on Windows.
(function installHideChildWindowsHook() {
  var MARK = Symbol.for('aiart.hideChildWindows.patched');
  if (globalThis[MARK]) return;
  globalThis[MARK] = true;
  try {
    var childProcess = require('node:child_process');
    var isOptions = function (value) {
      return value !== null && typeof value === 'object' && !Array.isArray(value);
    };
    // Copy the caller's options instead of mutating them, then force windowsHide on.
    var hide = function (options) {
      var next = isOptions(options) ? Object.assign({}, options) : {};
      next.windowsHide = true;
      return next;
    };
    var mark = function (fn) {
      fn[MARK] = true;
      return fn;
    };
    // (command[, args][, options]) shape: spawn / spawnSync / fork / execFileSync
    var patchSpawnLike = function (name) {
      var original = childProcess[name];
      if (typeof original !== 'function' || original[MARK]) return;
      childProcess[name] = mark(function (command, args, options) {
        if (Array.isArray(args) || args === undefined || args === null) {
          return original.call(this, command, args, hide(options));
        }
        return original.call(this, command, hide(args));
      });
    };
    // (command[, options][, callback]) shape: exec
    var patchExec = function (name) {
      var original = childProcess[name];
      if (typeof original !== 'function' || original[MARK]) return;
      childProcess[name] = mark(function (command, options, callback) {
        if (typeof options === 'function') {
          return original.call(this, command, hide(undefined), options);
        }
        return original.call(this, command, hide(options), callback);
      });
    };
    // (file[, args][, options][, callback]) shape: execFile (args / options / callback optional)
    var patchExecFile = function (name) {
      var original = childProcess[name];
      if (typeof original !== 'function' || original[MARK]) return;
      childProcess[name] = mark(function (file) {
        var rest = Array.prototype.slice.call(arguments, 1);
        var callback = typeof rest[rest.length - 1] === 'function' ? rest.pop() : undefined;
        var hasArgs = Array.isArray(rest[0]);
        var forwarded = [file, hasArgs ? rest[0] : undefined, hide(hasArgs ? rest[1] : rest[0])];
        if (callback) forwarded.push(callback);
        return original.apply(this, forwarded);
      });
    };
    // (command[, options]) shape: execSync
    var patchCommandOptions = function (name) {
      var original = childProcess[name];
      if (typeof original !== 'function' || original[MARK]) return;
      childProcess[name] = mark(function (command, options) {
        return original.call(this, command, hide(options));
      });
    };
    patchSpawnLike('spawn');
    patchSpawnLike('spawnSync');
    patchSpawnLike('fork');
    patchSpawnLike('execFileSync');
    patchExec('exec');
    patchExecFile('execFile');
    patchCommandOptions('execSync');
  } catch (error) {
    // Never block dsh startup: failing here only means losing this safety net.
  }
})();
`
