import { describe, expect, it } from 'vitest'
import { pickSpatialWorldIdFromJobs, pickSpatialWorldJobs } from '@shared/videoJob'
import type { VideoJobRecord } from '@shared/videoJob'

/**
 * 找回 world_id 的挑选规则（与主进程共用 `@shared/videoJob` 里那一份实现）。
 *
 * `world_id` 只活在节点出口值（`spatialWorldId`）与任务记录（`resourceId`）两处，
 * 而出口值在历史版本的若干条回写路径上被洗掉过。世界生成的积分**已经花过**，
 * 所以导出前允许按「产出这个模型的节点」去任务记录里补一次 —— 但必须是**同一条世界生成任务**：
 * 猜错就是拿别人的世界去导出，宁可报「没有 world_id」。
 */
function worldJob(patch: Partial<VideoJobRecord> = {}): VideoJobRecord {
  return {
    version: 1,
    kind: 'spatialWorld',
    localJobId: 'job-1',
    providerJobId: 'op-1',
    pollingUrl: 'op-1',
    providerInstanceId: 'p1',
    model: 'marble-1.1',
    prompt: 'a quiet alley',
    status: 'succeeded',
    progress: 100,
    source: 'graph',
    resourceId: 'wl-world-42',
    graphBinding: { nodeId: 'node-world', assetId: 'asset-host' },
    createdAt: '2026-10-05T05:00:00.000Z',
    submittedAt: '2026-10-05T05:00:00.000Z',
    updatedAt: '2026-10-05T05:09:00.000Z',
    ...patch
  }
}

describe('pickSpatialWorldIdFromJobs', () => {
  it('recovers the id of the world generated by that node', () => {
    expect(pickSpatialWorldIdFromJobs([worldJob()], { nodeId: 'node-world' })).toBe('wl-world-42')
    // 节点对不上时按模型资产 id 兜（同一张图里可能换过生成节点）
    expect(
      pickSpatialWorldIdFromJobs([worldJob({ graphBinding: { assetId: 'asset-host' } })], {
        nodeId: 'other-node',
        assetId: 'asset-host'
      })
    ).toBe('wl-world-42')
  })

  it('never guesses from an unrelated or unusable record', () => {
    // 别的节点生成的世界：宁可报「没有 world_id」，也不能拿别人的世界去导出
    expect(pickSpatialWorldIdFromJobs([worldJob()], { nodeId: 'node-other' })).toBeUndefined()
    // 没有 resourceId（生成阶段没取到 id 的记录）
    expect(
      pickSpatialWorldIdFromJobs([worldJob({ resourceId: undefined })], { nodeId: 'node-world' })
    ).toBeUndefined()
    // 还没成功的记录
    expect(
      pickSpatialWorldIdFromJobs([worldJob({ status: 'running' })], { nodeId: 'node-world' })
    ).toBeUndefined()
    // 3D 模型任务的 resourceId 不是 World.id
    expect(
      pickSpatialWorldIdFromJobs([worldJob({ kind: 'model3d' })], { nodeId: 'node-world' })
    ).toBeUndefined()
    expect(pickSpatialWorldIdFromJobs([], { nodeId: 'node-world' })).toBeUndefined()
    // 没有任何线索时不去翻记录
    expect(pickSpatialWorldIdFromJobs([worldJob()], {})).toBeUndefined()
  })
})

describe('pickSpatialWorldJobs', () => {
  /**
   * 记录里没有 `resourceId` 时仍要给出候选：主进程会拿它的 operation id
   * 再问上游一次（`/operations/{id}` 的响应里带 World 对象）。
   */
  it('still returns the candidate when the record has no stored id yet', () => {
    const unstored = worldJob({ resourceId: undefined })
    const candidates = pickSpatialWorldJobs([unstored], { nodeId: 'node-world' })
    expect(candidates).toHaveLength(1)
    expect(candidates[0]!.providerJobId).toBe('op-1')
    // 但本地取 id 仍然取不到 —— 得靠主进程去问上游
    expect(pickSpatialWorldIdFromJobs([unstored], { nodeId: 'node-world' })).toBeUndefined()
  })

  it('orders node matches before asset matches', () => {
    const byNode = worldJob({ localJobId: 'by-node', graphBinding: { nodeId: 'node-world' } })
    const byAsset = worldJob({
      localJobId: 'by-asset',
      resourceId: 'wl-other',
      graphBinding: { nodeId: 'someone-else', assetId: 'asset-host' }
    })
    const candidates = pickSpatialWorldJobs([byAsset, byNode], {
      nodeId: 'node-world',
      assetId: 'asset-host'
    })
    expect(candidates.map((job) => job.localJobId)).toEqual(['by-node', 'by-asset'])
  })
})
