/**
 * 人形简单骨架：导入后按网格端点 + 边连通估计关节，再 ARMATURE_AUTO。
 * 固定比例只在端点走不通时兜底。
 */
import {
  HUMANOID_BONE_NAMES,
  type HumanoidBoneSpec
} from './blenderHumanoidLandmarks'

export const BLENDER_HUMANOID_RIG_MARKER = 'AIAE_HUMANOID_RIG'
export const BLENDER_HUMANOID_BONE_NAMES = HUMANOID_BONE_NAMES

/** 仅作路径失败时的兜底，主路径读 mesh。 */
export const BLENDER_HUMANOID_BONE_SPECS: ReadonlyArray<HumanoidBoneSpec> = [
  { name: 'Hips', parent: '', head: [0, 0.02, 0.5], tail: [0, 0.0, 0.56] },
  { name: 'Spine', parent: 'Hips', head: [0, 0.0, 0.56], tail: [0, 0.0, 0.66] },
  { name: 'Chest', parent: 'Spine', head: [0, 0.0, 0.66], tail: [0, 0.0, 0.76] },
  { name: 'Neck', parent: 'Chest', head: [0, 0.0, 0.76], tail: [0, 0.0, 0.84] },
  { name: 'Head', parent: 'Neck', head: [0, 0.0, 0.84], tail: [0, 0.02, 0.98] },
  { name: 'L_Shoulder', parent: 'Chest', head: [0.1, 0.02, 0.8], tail: [0.2, 0.02, 0.8] },
  { name: 'L_UpperArm', parent: 'L_Shoulder', head: [0.2, 0.02, 0.8], tail: [0.38, 0.04, 0.72] },
  { name: 'L_ForeArm', parent: 'L_UpperArm', head: [0.38, 0.04, 0.72], tail: [0.54, 0.04, 0.6] },
  { name: 'L_Hand', parent: 'L_ForeArm', head: [0.54, 0.04, 0.6], tail: [0.66, 0.04, 0.54] },
  { name: 'R_Shoulder', parent: 'Chest', head: [-0.1, 0.02, 0.8], tail: [-0.2, 0.02, 0.8] },
  { name: 'R_UpperArm', parent: 'R_Shoulder', head: [-0.2, 0.02, 0.8], tail: [-0.38, 0.04, 0.72] },
  { name: 'R_ForeArm', parent: 'R_UpperArm', head: [-0.38, 0.04, 0.72], tail: [-0.54, 0.04, 0.6] },
  { name: 'R_Hand', parent: 'R_ForeArm', head: [-0.54, 0.04, 0.6], tail: [-0.66, 0.04, 0.54] },
  { name: 'L_UpLeg', parent: 'Hips', head: [0.11, 0.02, 0.5], tail: [0.12, 0.03, 0.28] },
  { name: 'L_LoLeg', parent: 'L_UpLeg', head: [0.12, 0.03, 0.28], tail: [0.11, 0.04, 0.06] },
  { name: 'L_Foot', parent: 'L_LoLeg', head: [0.11, 0.04, 0.06], tail: [0.11, 0.16, 0.02] },
  { name: 'L_Toes', parent: 'L_Foot', head: [0.11, 0.16, 0.02], tail: [0.11, 0.24, 0.02] },
  { name: 'R_UpLeg', parent: 'Hips', head: [-0.11, 0.02, 0.5], tail: [-0.12, 0.03, 0.28] },
  { name: 'R_LoLeg', parent: 'R_UpLeg', head: [-0.12, 0.03, 0.28], tail: [-0.11, 0.04, 0.06] },
  { name: 'R_Foot', parent: 'R_LoLeg', head: [-0.11, 0.04, 0.06], tail: [-0.11, 0.16, 0.02] },
  { name: 'R_Toes', parent: 'R_Foot', head: [-0.11, 0.16, 0.02], tail: [-0.11, 0.24, 0.02] }
]

export const BLENDER_HUMANOID_RIG_CODE = [
  `# ${BLENDER_HUMANOID_RIG_MARKER}`,
  'import bpy',
  'if bpy.context.view_layer.objects.active is not None:',
  '    bpy.ops.object.mode_set(mode="OBJECT")',
  'meshes = [o for o in bpy.data.objects if o.type == "MESH"]',
  'if not meshes:',
  "    raise RuntimeError('no mesh')",
  'pts = []',
  'adj = []',
  'for mesh in meshes:',
  '    mw = mesh.matrix_world',
  '    base = len(pts)',
  '    for v in mesh.data.vertices:',
  '        p = mw @ v.co',
  '        pts.append((p.x, p.y, p.z))',
  '        adj.append([])',
  '    for e in mesh.data.edges:',
  '        a = base + e.vertices[0]',
  '        b = base + e.vertices[1]',
  '        adj[a].append(b)',
  '        adj[b].append(a)',
  'if len(pts) < 8:',
  "    raise RuntimeError('too few verts')",
  'xs = [p[0] for p in pts]',
  'ys = [p[1] for p in pts]',
  'zs = [p[2] for p in pts]',
  'minx, maxx = min(xs), max(xs)',
  'miny, maxy = min(ys), max(ys)',
  'minz, maxz = min(zs), max(zs)',
  'sx = max(maxx - minx, 0.001)',
  'sy = max(maxy - miny, 0.001)',
  'sz = max(maxz - minz, 0.001)',
  'if sz >= sy and sz >= sx:',
  '    up, side, fwd = 2, 0, 1',
  '    umin, ur = minz, sz',
  'elif sx >= sy and sx >= sz:',
  '    up, side, fwd = 0, 2, 1',
  '    umin, ur = minx, sx',
  'else:',
  '    up, side, fwd = 1, 0, 2',
  '    umin, ur = miny, sy',
  'smin = min(p[side] for p in pts)',
  'smax = max(p[side] for p in pts)',
  'sr = max(smax - smin, 0.001)',
  'cx = (smin + smax) * 0.5',
  'def unorm(p):',
  '    return (p[up] - umin) / ur',
  'def sidev(p):',
  '    return p[side]',
  'def fwdv(p):',
  '    return p[fwd]',
  'midw = [abs(sidev(p) - cx) for p in pts if 0.35 <= unorm(p) <= 0.7]',
  'midw.sort()',
  'torso_r = midw[int(len(midw) * 0.35)] if midw else sr * 0.2',
  'if torso_r < sr * 0.14:',
  '    torso_r = sr * 0.14',
  'def lerp(a, b, t):',
  '    return (a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t, a[2] + (b[2] - a[2]) * t)',
  'def avg(a, b):',
  '    return ((a[0] + b[0]) * 0.5, (a[1] + b[1]) * 0.5, (a[2] + b[2]) * 0.5)',
  'def ensure(a, b):',
  '    dx, dy, dz = b[0] - a[0], b[1] - a[1], b[2] - a[2]',
  '    if dx * dx + dy * dy + dz * dz < (ur * 0.012) ** 2:',
  '        return (a[0], a[1], a[2] + ur * 0.012)',
  '    return b',
  'def centroid(lo, hi, rad):',
  '    x = y = z = n = 0.0',
  '    for p in pts:',
  '        u = unorm(p)',
  '        if u < lo or u > hi:',
  '            continue',
  '        if abs(sidev(p) - cx) > rad:',
  '            continue',
  '        x += p[0]',
  '        y += p[1]',
  '        z += p[2]',
  '        n += 1.0',
  '    if n < 1:',
  '        return None',
  '    return (x / n, y / n, z / n)',
  'def bfs_until(start):',
  '    prev = {start: -1}',
  '    q = [start]',
  '    qi = 0',
  '    hit = -1',
  '    while qi < len(q):',
  '        i = q[qi]',
  '        qi += 1',
  '        if i != start and abs(sidev(pts[i]) - cx) <= torso_r * 1.25:',
  '            hit = i',
  '            break',
  '        for j in adj[i]:',
  '            if j not in prev:',
  '                prev[j] = i',
  '                q.append(j)',
  '    if hit < 0:',
  '        return []',
  '    path = []',
  '    i = hit',
  '    while i >= 0:',
  '        path.append(i)',
  '        i = prev[i]',
  '    path.reverse()',
  '    return path',
  'def path_pt(path, t):',
  '    if not path:',
  '        return pts[0]',
  '    idx = int(round((len(path) - 1) * t))',
  '    if idx < 0:',
  '        idx = 0',
  '    if idx >= len(path):',
  '        idx = len(path) - 1',
  '    return pts[path[idx]]',
  'def highest_on_path(path):',
  '    idx = len(path) - 1',
  '    best = -1e18',
  '    k = 0',
  '    while k < len(path):',
  '        u = pts[path[k]][up]',
  '        if u >= best:',
  '            best = u',
  '            idx = k',
  '        k += 1',
  '    return pts[path[idx]], idx',
  'def path_pt_len(path, t, last):',
  '    n = last + 1',
  '    if n < 1:',
  '        return path_pt(path, t)',
  '    idx = int(round((n - 1) * t))',
  '    if idx < 0:',
  '        idx = 0',
  '    if idx >= len(path):',
  '        idx = len(path) - 1',
  '    return pts[path[idx]]',
  'def pick_extreme(sign, lo, hi, mode):',
  '    best = -1',
  '    score = 1e18 if mode == "upMin" else -1e18',
  '    i = 0',
  '    while i < len(pts):',
  '        p = pts[i]',
  '        u = unorm(p)',
  '        s = sidev(p) - cx',
  '        if u >= lo and u <= hi and ((sign > 0 and s > 0) or (sign < 0 and s < 0)):',
  '            if mode == "side":',
  '                v = abs(s)',
  '                if v > score:',
  '                    score = v',
  '                    best = i',
  '            elif mode == "upMin":',
  '                v = p[up]',
  '                if v < score:',
  '                    score = v',
  '                    best = i',
  '            else:',
  '                v = fwdv(p)',
  '                if v > score:',
  '                    score = v',
  '                    best = i',
  '        i += 1',
  '    return best',
  'def pick_hand(sign):',
  '    ranked = []',
  '    i = 0',
  '    while i < len(pts):',
  '        p = pts[i]',
  '        u = unorm(p)',
  '        s = sidev(p) - cx',
  '        if 0.28 <= u <= 0.9 and ((sign > 0 and s > 0) or (sign < 0 and s < 0)):',
  '            ranked.append((abs(s), i))',
  '        i += 1',
  '    ranked.sort(reverse=True)',
  '    best_i = ranked[0][1] if ranked else -1',
  '    best_path = []',
  '    best_score = -1e18',
  '    k = 0',
  '    limit = min(20, len(ranked))',
  '    while k < limit:',
  '        i = ranked[k][1]',
  '        path = bfs_until(i)',
  '        if len(path) >= 4:',
  '            top_u = max(unorm(pts[j]) for j in path)',
  '            if top_u <= 0.93:',
  '                end_u = unorm(pts[path[-1]])',
  '                score = abs(sidev(pts[i]) - cx)',
  '                if end_u > 0.52:',
  '                    score += sr * 0.15',
  '                if score > best_score:',
  '                    best_score = score',
  '                    best_i = i',
  '                    best_path = path',
  '        k += 1',
  '    return best_i, best_path',
  'head = centroid(0.88, 1.0, sr * 0.22)',
  'if head is None:',
  '    hi = pick_extreme(1, 0.85, 1.0, "side")',
  '    head = pts[hi] if hi >= 0 else pts[0]',
  'lh_i, lh_path = pick_hand(1)',
  'rh_i, rh_path = pick_hand(-1)',
  'lf_i = pick_extreme(1, 0.0, 0.28, "upMin")',
  'rf_i = pick_extreme(-1, 0.0, 0.28, "upMin")',
  'lt_i = pick_extreme(1, 0.0, 0.12, "fwdMax")',
  'rt_i = pick_extreme(-1, 0.0, 0.12, "fwdMax")',
  'l_foot = pts[lf_i] if lf_i >= 0 else head',
  'r_foot = pts[rf_i] if rf_i >= 0 else l_foot',
  'l_toe = pts[lt_i] if lt_i >= 0 else l_foot',
  'r_toe = pts[rt_i] if rt_i >= 0 else r_foot',
  'l_hand = pts[lh_i] if lh_i >= 0 else head',
  'r_hand = pts[rh_i] if rh_i >= 0 else head',
  'lf_path = bfs_until(lf_i) if lf_i >= 0 else []',
  'rf_path = bfs_until(rf_i) if rf_i >= 0 else []',
  'l_sho, l_sho_i = highest_on_path(lh_path) if len(lh_path) >= 4 else (lerp(l_hand, head, 0.72), 0)',
  'r_sho, r_sho_i = highest_on_path(rh_path) if len(rh_path) >= 4 else (lerp(r_hand, head, 0.72), 0)',
  'l_elb = path_pt_len(lh_path, 0.5, l_sho_i) if len(lh_path) >= 4 else lerp(l_sho, l_hand, 0.5)',
  'r_elb = path_pt_len(rh_path, 0.5, r_sho_i) if len(rh_path) >= 4 else lerp(r_sho, r_hand, 0.5)',
  'l_wri = path_pt(lh_path, 0.12) if len(lh_path) >= 4 else lerp(l_elb, l_hand, 0.72)',
  'r_wri = path_pt(rh_path, 0.12) if len(rh_path) >= 4 else lerp(r_elb, r_hand, 0.72)',
  'l_hip = path_pt(lf_path, 1.0) if len(lf_path) >= 4 else lerp(l_foot, l_sho, 0.52)',
  'r_hip = path_pt(rf_path, 1.0) if len(rf_path) >= 4 else lerp(r_foot, r_sho, 0.52)',
  'sho_u = (unorm(l_sho) + unorm(r_sho)) * 0.5',
  'hip_u = (unorm(l_hip) + unorm(r_hip)) * 0.5',
  'if sho_u - hip_u < 0.12:',
  '    raised = umin + ur * max(0.22, sho_u - 0.32)',
  '    l_hip = (l_hip[0], l_hip[1], l_hip[2])',
  '    r_hip = (r_hip[0], r_hip[1], r_hip[2])',
  '    l_list = [l_hip[0], l_hip[1], l_hip[2]]',
  '    r_list = [r_hip[0], r_hip[1], r_hip[2]]',
  '    l_list[up] = raised',
  '    r_list[up] = raised',
  '    l_hip = (l_list[0], l_list[1], l_list[2])',
  '    r_hip = (r_list[0], r_list[1], r_list[2])',
  'l_knee = path_pt(lf_path, 0.5) if len(lf_path) >= 4 else lerp(l_hip, l_foot, 0.5)',
  'r_knee = path_pt(rf_path, 0.5) if len(rf_path) >= 4 else lerp(r_hip, r_foot, 0.5)',
  'hips = avg(l_hip, r_hip)',
  'chest = centroid((unorm(hips) + sho_u) * 0.5 - 0.04, sho_u + 0.02, torso_r)',
  'if chest is None:',
  '    chest = lerp(hips, head, 0.62)',
  'neck = centroid(sho_u - 0.02, unorm(head) - 0.04, torso_r * 0.7)',
  'if neck is None:',
  '    neck = lerp(chest, head, 0.45)',
  'spine = lerp(hips, chest, 0.45)',
  'bones = [',
  "    ('Hips', '', hips, spine),",
  "    ('Spine', 'Hips', spine, chest),",
  "    ('Chest', 'Spine', chest, neck),",
  "    ('Neck', 'Chest', neck, lerp(neck, head, 0.55)),",
  "    ('Head', 'Neck', lerp(neck, head, 0.55), head),",
  "    ('L_Shoulder', 'Chest', lerp(neck, l_sho, 0.35), l_sho),",
  "    ('L_UpperArm', 'L_Shoulder', l_sho, l_elb),",
  "    ('L_ForeArm', 'L_UpperArm', l_elb, l_wri),",
  "    ('L_Hand', 'L_ForeArm', l_wri, l_hand),",
  "    ('R_Shoulder', 'Chest', lerp(neck, r_sho, 0.35), r_sho),",
  "    ('R_UpperArm', 'R_Shoulder', r_sho, r_elb),",
  "    ('R_ForeArm', 'R_UpperArm', r_elb, r_wri),",
  "    ('R_Hand', 'R_ForeArm', r_wri, r_hand),",
  "    ('L_UpLeg', 'Hips', l_hip, l_knee),",
  "    ('L_LoLeg', 'L_UpLeg', l_knee, l_foot),",
  "    ('L_Foot', 'L_LoLeg', l_foot, lerp(l_foot, l_toe, 0.65)),",
  "    ('L_Toes', 'L_Foot', lerp(l_foot, l_toe, 0.65), l_toe),",
  "    ('R_UpLeg', 'Hips', r_hip, r_knee),",
  "    ('R_LoLeg', 'R_UpLeg', r_knee, r_foot),",
  "    ('R_Foot', 'R_LoLeg', r_foot, lerp(r_foot, r_toe, 0.65)),",
  "    ('R_Toes', 'R_Foot', lerp(r_foot, r_toe, 0.65), r_toe),",
  ']',
  'olds = [o for o in bpy.data.objects if o.type == "ARMATURE"]',
  'for o in olds:',
  '    bpy.data.objects.remove(o, do_unlink=True)',
  "arm_data = bpy.data.armatures.new('Armature')",
  "arm_obj = bpy.data.objects.new('Armature', arm_data)",
  'bpy.context.collection.objects.link(arm_obj)',
  'bpy.context.view_layer.objects.active = arm_obj',
  'arm_obj.select_set(True)',
  'bpy.ops.object.mode_set(mode="EDIT")',
  'created = {}',
  'ebones = arm_obj.data.edit_bones',
  'for spec in bones:',
  '    bone = ebones.new(spec[0])',
  '    bone.head = spec[2]',
  '    bone.tail = ensure(spec[2], spec[3])',
  '    if spec[1] and spec[1] in created:',
  '        bone.parent = created[spec[1]]',
  '        bone.use_connect = False',
  '    created[spec[0]] = bone',
  'bpy.ops.object.mode_set(mode="OBJECT")',
  'for mesh in meshes:',
  '    for obj in bpy.data.objects:',
  '        obj.select_set(False)',
  '    mesh.select_set(True)',
  '    arm_obj.select_set(True)',
  '    bpy.context.view_layer.objects.active = arm_obj',
  '    bpy.ops.object.parent_set(type="ARMATURE_AUTO")',
  "print('AIAE_HUMANOID_RIG_OK', len(created))"
].join('\n')

export function humanoidSimpleRecipe(): string {
  return [
    'Expanded recipe (humanoid-simple, 21 bones):',
    `After importing input.glb, run this execute_blender_code verbatim. Place bones from mesh vertices and edge walks (hands/feet to torso). Do not invent head/tail. Marker: ${BLENDER_HUMANOID_RIG_MARKER}.`,
    BLENDER_HUMANOID_RIG_CODE
  ].join('\n')
}
